import React, { useEffect, useState } from 'react';
import './style.css'
const WhatIs = props => {

    return (
<div className="feedbackCardContainer__feedbackCardContainer pageComponent" icn="iconS_homePage_48 icon_yellowQuote" title=" What our users have to say..." cardtype="FeedbackCard" data="[object Object]" pagename="rentAgreement" topmost="true" data-label="LANDING_PAGE.TESTIMONIAL" id="LANDING_PAGE.TESTIMONIAL" style={{marginBottom:'20px'}}><div className="bgCardContainer__bgCardContainer"><div className="bgCardContainer__cardBg undefined" /><div className="bgCardContainer__bgCardTitle"><i className="iconS_homePage_48 icon_yellowQuote" /><h3 className="title_bold" style={{marginBottom:'20px'}}> What our users have to say...</h3></div><div className="spacer8" /><div className="bgCardContainer__cardWrap"><div className="slider__xidSliderWrap"><div className="feedbackCard__feedbackCard"><div className="feedbackCard__userprofile"><div><div className="Avatar__avatars40_color4"><div><div>SS</div></div></div></div><div><div className="list_header_semiBold spacer2">Sangeeta Singh</div><div className="caption_strong_medium">Owner, New Delhi</div></div></div><div className="spacer10" /><div className="body_small ellipsis2Lines">Several options are available in terms of locations, property type and price. It would be great if 99acres provides more preferences in tier II cities also.</div><div className="spacer8" />
{/* <a className="input_counter_focused" href="javascript:void(0)">Read more</a> */}
</div><div className="feedbackCard__feedbackCard"><div className="feedbackCard__userprofile"><div><div className="Avatar__avatars40_color4"><div><div>TK</div></div></div></div><div><div className="list_header_semiBold spacer2">Tina Kapoor</div><div className="caption_strong_medium">Owner, Chennai</div></div></div><div className="spacer10" /><div className="body_small ellipsis2Lines">Creativity combined with excellent technical capabilities, I am thankful to 99acres.com for its services</div><div className="spacer8" /><a className="input_counter_focused" href="javascript:void(0)">Read more</a></div><div className="feedbackCard__feedbackCard"><div className="feedbackCard__userprofile"><div><div className="Avatar__avatars40_color4"><div><div>HM</div></div></div></div><div><div className="list_header_semiBold spacer2">Hasibuddin Mohammad</div><div className="caption_strong_medium">Dealer,Mumbai</div></div></div><div className="spacer10" /><div className="body_small ">Prompt response and offered constant assistance after posting my ad on the website</div><div className="spacer20" /></div></div></div></div></div> );
};

export default WhatIs;
